name: MCP Security Scan - Scheduled

on:
  schedule:
    # Run security scan every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  daily-security-scan:
    runs-on: ubuntu-latest
    name: Daily Security Audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MCP Server
        run: |
          # Start your MCP server
          npm install
          npm start &
          sleep 10

      - name: Run MCP Security Tests
        uses: ApInference/mcp-testbench@v1
        with:
          target: 'http://localhost:8000'
          fail-on-score: 'D'  # Only fail on critical issues
          output-dir: './daily-security-reports'

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Daily Security Scan Failed',
              body: `The scheduled security scan has detected issues.

View the full report in the [workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}).

**Action Required:** Review and address security vulnerabilities.`,
              labels: ['security', 'automated']
            });

      - name: Archive Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: daily-security-report-${{ github.run_number }}
          path: ./daily-security-reports/
          retention-days: 90
